const $ = (s) => document.querySelector(s);
const SUPABASE_URL = 'https://ijkesdecfubukdblllpo.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_8X5lSbfWx-aNAdqSp6H5RQ_F8iHLW2f';
let supabaseClient = null;
let currentUser = null;
let cloudRatedKeys = new Set();
const cafeKey = (name, address) => `${String(name || '').trim().toLowerCase()}|${String(address || '').trim().toLowerCase()}`;
function initSupabase() { if (!window.supabase) return; supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY); supabaseClient.auth.getUser().then(({ data }) => { currentUser = data.user; updateAuthButton(); }); supabaseClient.auth.onAuthStateChange((_event, session) => { currentUser = session?.user || null; updateAuthButton(); }); }
function updateAuthButton() { const button = $('#authButton'); if (!button) return; button.textContent = currentUser ? `${currentUser.email} · 로그아웃` : '로그인'; button.onclick = currentUser ? async () => { await supabaseClient.auth.signOut(); toast('로그아웃했습니다.'); } : openAuthModal; }
function openAuthModal() { const overlay = document.createElement('div'); overlay.className = 'auth-modal'; overlay.innerHTML = `<form class="auth-dialog"><button type="button" class="auth-close">×</button><h3>카페 파인더 로그인</h3><input name="email" type="email" placeholder="이메일" required /><input name="password" type="password" placeholder="비밀번호(6자 이상)" minlength="6" required /><button type="submit">로그인</button><p><button type="button" class="auth-switch">처음인가요? 회원가입</button></p></form>`; document.body.appendChild(overlay); const form = overlay.querySelector('form'); overlay.querySelector('.auth-close').onclick = () => overlay.remove(); overlay.querySelector('.auth-switch').onclick = () => { form.querySelector('h3').textContent = '카페 파인더 회원가입'; form.querySelector('button[type=submit]').textContent = '회원가입'; form.querySelector('.auth-switch').textContent = '이미 계정이 있어요? 로그인'; form.dataset.signup = form.dataset.signup === '1' ? '0' : '1'; }; form.onsubmit = async (event) => { event.preventDefault(); const email = form.email.value; const password = form.password.value; const result = form.dataset.signup === '1' ? await supabaseClient.auth.signUp({ email, password }) : await supabaseClient.auth.signInWithPassword({ email, password }); if (result.error) return toast(result.error.message); overlay.remove(); toast(form.dataset.signup === '1' ? '회원가입 요청을 완료했습니다.' : '로그인했습니다.'); }; }
async function saveVisitToSupabase(item, score) { if (!currentUser || !supabaseClient) return; const { error } = await supabaseClient.from('visit_history').insert({ user_id: currentUser.id, cafe_name: item.name, address: item.address || '', purpose: item.purpose || '', visit_date: item.date, work_rating: score, cafe_data: item }); if (error) toast(`Supabase 저장 오류: ${error.message}`); }
initSupabase();
const toast = (message) => { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2200); };
document.querySelectorAll('.purpose').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.purpose').forEach((item) => item.classList.remove('selected')); button.classList.add('selected'); }));
document.querySelectorAll('.chip').forEach((button) => button.addEventListener('click', () => button.classList.toggle('selected')));

let cafeMap;
let cafeMapMarkers;
const defaultMapCenter = [37.5665, 126.978];
const quickMapCenters = { 서울: [37.5665, 126.978], 성수: [37.5446, 127.0559], 강남: [37.4979, 127.0276], 홍대: [37.5563, 126.9236], 부산: [35.1796, 129.0756], 대구: [35.8714, 128.6014], 인천: [37.4563, 126.7052], 광주: [35.1595, 126.8526], 대전: [36.3504, 127.3845], 울산: [35.5384, 129.3114], 제주: [33.4996, 126.5312], 세종: [36.4801, 127.2890], 수원: [37.2636, 127.0286], 전주: [35.8242, 127.1480], 춘천: [37.8813, 127.7298], 청주: [36.6424, 127.4890], 포항: [36.0190, 129.3435], 창원: [35.2280, 128.6811] };
function getQuickMapCenter(location) { const key = Object.keys(quickMapCenters).find((name) => String(location || '').includes(name)); return key ? quickMapCenters[key] : defaultMapCenter; }
async function geocodeCafe(name, address, location) { const response = await fetch(`/api/geocode?name=${encodeURIComponent(name || '')}&address=${encodeURIComponent(address || '')}&location=${encodeURIComponent(location || '')}`); if (!response.ok) throw new Error(`주소 변환 실패: ${response.status}`); return response.json(); }
async function updateCafeMap(location, cafes = []) {
  if (!window.L || !$('#cafeMap')) return;
  if (!cafeMap) { cafeMap = L.map('cafeMap').setView(defaultMapCenter, 13); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '&copy; OpenStreetMap contributors' }).addTo(cafeMap); cafeMapMarkers = L.layerGroup().addTo(cafeMap); }
  cafeMap.setView(getQuickMapCenter(location), 13, { animate: false });
  cafeMapMarkers.clearLayers();
  const results = await Promise.all(cafes.slice(0, 3).map(async (cafe) => {
    try { const place = await geocodeCafe(cafe.name, cafe.address, location); return place && Number.isFinite(Number(place.lat)) && Number.isFinite(Number(place.lon)) ? { cafe, point: [Number(place.lat), Number(place.lon)] } : null; }
    catch (error) { console.warn('카페 주소 좌표 변환 실패', cafe.address, error); return null; }
  }));
  const points = results.filter(Boolean).map(({ cafe, point }) => { L.marker(point).addTo(cafeMapMarkers).bindPopup(`<strong>${cafe.name || '추천 카페'}</strong><br>${cafe.address || ''}`); return point; });
  if (points.length) cafeMap.fitBounds(L.latLngBounds(points), { padding: [30, 30], maxZoom: 16 });
  else { try { const place = await geocodeCafe('', '', location); if (place && Number.isFinite(Number(place.lat))) cafeMap.setView([Number(place.lat), Number(place.lon)], 14); } catch (error) { console.warn('검색 지역 좌표 변환 실패', location, error); cafeMap.setView(defaultMapCenter, 12); } }
  setTimeout(() => cafeMap.invalidateSize(), 100);
}
let googleGeocoder;
let googleMapReady;
function loadGoogleMap() {
  if (googleMapReady) return googleMapReady;
  googleMapReady = fetch('/api/maps-config').then((response) => response.json()).then((config) => new Promise((resolve, reject) => {
    if (!config.key) return reject(new Error('Google Maps API 키가 설정되지 않았습니다.'));
    window.initGoogleMap = () => { googleMap = new google.maps.Map($('#googleMap'), { center: { lat: 37.5665, lng: 126.9780 }, zoom: 12, mapTypeControl: false, streetViewControl: false, fullscreenControl: false }); googleGeocoder = new google.maps.Geocoder(); resolve(); };
    const script = document.createElement('script'); script.src = `https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(config.key)}&callback=initGoogleMap`; script.async = true; script.defer = true; script.onerror = () => reject(new Error('Google Maps를 불러오지 못했습니다. API 제한 설정을 확인해주세요.')); document.head.appendChild(script);
  }));
  return googleMapReady;
}
function plotCafes(cafes) { if (!googleGeocoder) return; cafes.forEach((cafe) => { if (!cafe.address) return; googleGeocoder.geocode({ address: cafe.address }, (results, status) => { if (status !== 'OK' || !results[0]) return; const marker = new google.maps.Marker({ map: googleMap, position: results[0].geometry.location, title: cafe.name }); const info = new google.maps.InfoWindow({ content: `<strong>${cafe.name}</strong><br>${cafe.address}` }); marker.addListener('click', () => info.open({ map: googleMap, anchor: marker })); }); }); }

function renderCards(cafes, options = {}) {
  const excludedWords = ['스터디카페', '스터디 카페', '독서실', '스터디룸', '스터디 룸', '무인 스터디', '학원형 스터디'];
  cafes = cafes.filter((cafe) => !excludedWords.some((word) => `${cafe.name || ''} ${cafe.category || ''} ${cafe.address || ''}`.toLowerCase().includes(word)));
  if (!options.preview) updateCafeMap($('#location').value.trim(), cafes).catch(() => toast('주소를 지도에 표시하지 못했지만 추천 결과는 표시됩니다.'));
  $('#cards').innerHTML = cafes.slice(0, 3).length ? cafes.slice(0, 3).map((cafe, index) => { const item = {name:cafe.name,address:cafe.address,date:new Date().toISOString().slice(0,10),purpose:$('.purpose.selected').dataset.purpose}; const rated = cloudRatedKeys.has(cafeKey(cafe.name, cafe.address)) || JSON.parse(localStorage.getItem('cafeHistory') || '[]').some((saved) => cafeKey(saved.name, saved.address) === cafeKey(cafe.name, cafe.address)); return `<article class="cafe-card"><div class="cafe-content"><h3>${index + 1}. ${cafe.name}</h3><div class="meta">${cafe.address || '주소 정보 없음'}</div><div class="details compact-details"><span><b>영업시간</b>${cafe.businessHours || '정보 확인 필요'}</span><span><b>혼잡도</b>${cafe.crowdLevel || '정보 확인 필요'}</span><span><b>자리 유형</b>${cafe.seatType || '정보 확인 필요'}</span><span><b>소음 수준</b>${cafe.noiseLevel || '정보 확인 필요'}</span><span><b>콘센트</b>${cafe.outlet || '정보 확인 필요'}</span><span><b>대표 메뉴</b>${cafe.signatureMenu || '정보 확인 필요'}</span></div>${options.preview ? '<small class="cache-note">최신 정보 확인 중</small>' : `<button class="history-save" ${rated ? 'disabled' : ''} data-cafe="${encodeURIComponent(JSON.stringify(item))}">${rated ? '평가 완료' : '방문 이력 저장'}</button>`}</div><a class="save" href="${cafe.url || '#'}" target="_blank" rel="noreferrer" title="장소 상세 보기">↗</a></article>`; }).join('') : '<div class="empty">검색 결과가 없습니다. 장소명이나 지역을 조금 더 구체적으로 입력해보세요.</div>';
  document.querySelectorAll('.history-save').forEach((button) => button.addEventListener('click', () => openRatingModal(button)));
}
function openRatingModal(button) { const item = JSON.parse(decodeURIComponent(button.dataset.cafe)); const overlay = document.createElement('div'); overlay.className = 'rating-modal'; overlay.innerHTML = `<div class="rating-dialog" role="dialog" aria-modal="true"><button class="rating-close" type="button" aria-label="닫기">×</button><h3>작업 효율을 평가해주세요</h3><p>${item.name}</p><div class="rating-stars">${[1,2,3,4,5].map((score) => `<button type="button" data-rating="${score}">★</button>`).join('')}</div><small>별점을 선택하면 방문 이력에 저장됩니다.</small></div>`; document.body.appendChild(overlay); const close = () => overlay.remove(); overlay.querySelector('.rating-close').addEventListener('click', close); overlay.addEventListener('click', (event) => { if (event.target === overlay) close(); }); const stars = [...overlay.querySelectorAll('[data-rating]')]; const paint = (score) => stars.forEach((item) => item.classList.toggle('active', Number(item.dataset.rating) <= score)); stars.forEach((star) => { star.addEventListener('mouseenter', () => paint(Number(star.dataset.rating))); star.addEventListener('click', () => { const score = Number(star.dataset.rating); paint(score); const history = JSON.parse(localStorage.getItem('cafeHistory') || '[]'); if (history.some((saved) => saved.name === item.name && saved.address === item.address)) { close(); toast('이미 저장된 방문 이력입니다.'); return; } item.rating = score; history.unshift(item); localStorage.setItem('cafeHistory', JSON.stringify(history)); button.textContent = '방문 이력 저장됨'; button.disabled = true; close(); renderHistory(); toast(`${score}점으로 방문 이력에 저장했습니다.`); }); }); }
async function renderResults() {
  const purpose = $('.purpose.selected').dataset.purpose, location = $('#location').value.trim(), people = $('#people').value, stay = $('#stay').value;
  const selected = [...document.querySelectorAll('.chip.selected')].map((item) => item.textContent.trim());
  if (!location) { toast('검색할 지역을 입력해주세요.'); $('#location').focus(); return; }
  $('#resultSummary').textContent = `${location} · ${purpose} · ${people} · ${stay} · ${selected.length}개 조건`;
  $('#cards').innerHTML = '<div class="empty">OpenAI 웹 검색으로 최신 카페 정보를 찾고 있습니다...</div>'; $('#results').classList.remove('hidden'); $('#results').scrollIntoView({ behavior: 'smooth' });
  const conditions = [location, '카페', `방문 목적: ${purpose}`, `방문 시간: ${$('#date').value || '시간 미지정'}`, `동행 인원: ${people}`, `체류 시간: ${stay}`, selected.length ? `필수 조건: ${selected.join(', ')}` : ''].filter(Boolean).join(' / ');
  const quickPreview = [1, 2, 3].map((index) => ({ name: `${location} 인근 카페 후보 ${index}`, address: `${location} 주변`, businessHours: '최신 정보 확인 중', crowdLevel: '정보 확인 필요', seatType: '정보 확인 필요', noiseLevel: '정보 확인 필요', outlet: '정보 확인 필요', signatureMenu: '정보 확인 필요', preview: true }));
  renderCards(quickPreview, { preview: true });
  updateCafeMap(location, []).catch(() => {});
  const cacheKey = `cafeSearch:${conditions}`;
  const cached = JSON.parse(localStorage.getItem(cacheKey) || 'null');
  if (cached?.results?.length) { renderCards(cached.results); $('#cards').insertAdjacentHTML('afterbegin', '<div class="cache-note">빠른 결과를 먼저 표시했습니다 · 최신 정보 확인 중</div>'); }
  try { const response = await fetch(`/api/search?query=${encodeURIComponent(conditions)}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'API 연결에 실패했습니다.'); localStorage.setItem(cacheKey, JSON.stringify({ results: payload.results || [], savedAt: Date.now() })); renderCards(payload.results || []); }
  catch (error) { $('#cards').innerHTML = `<div class="empty">${error.message}<br><small>서버의 .env 설정에 외부 API 키를 등록한 뒤 다시 검색해주세요.</small></div>`; }
}
function renderHistory() { const history = JSON.parse(localStorage.getItem('cafeHistory') || '[]').sort((a, b) => (b.rating || 0) - (a.rating || 0)); $('#historyList').innerHTML = history.length ? history.map((item, index) => `<div class="history-item"><div><h3>${item.name}</h3><small>${item.date} · ${item.purpose} · 작업 효율 ${'★'.repeat(item.rating || 0)}${'☆'.repeat(5 - (item.rating || 0))}</small></div><button class="history-delete" data-history-index="${index}" type="button">삭제</button></div>`).join('') : '<div class="empty">외부 검색 결과에서 장소를 확인한 뒤 방문 이력을 저장할 수 있습니다.</div>'; document.querySelectorAll('.history-delete').forEach((button) => button.addEventListener('click', () => { const items = JSON.parse(localStorage.getItem('cafeHistory') || '[]'); items.splice(Number(button.dataset.historyIndex), 1); localStorage.setItem('cafeHistory', JSON.stringify(items)); renderHistory(); toast('방문 이력을 삭제했습니다.'); })); }
function analyzePrompt() {
  const text = $('#prompt').value.trim();
  const purposeMap = [['집중 작업',['작업','업무','노트북']],['공부',['공부','스터디','시험']],['데이트',['데이트','연인']],['대화',['대화','친구']],['휴식',['휴식','힐링']],['모임',['모임','단체']]];
  const purpose = purposeMap.find(([, words]) => words.some((word) => text.includes(word)));
  if (purpose) document.querySelector(`[data-purpose="${purpose[0]}"]`).click();
  const place = text.match(/([^\s,]+(?:\s+[^\s,]+){0,3}?)(?:에서| 근처|의 카페)/);
  if (place) $('#location').value = place[1].replace(/^(오늘|내일|지금)\s+/, '').trim();
  const time = text.match(/(오늘|내일|지금)?\s*(오전|오후|저녁|밤)?\s*(\d{1,2})\s*시/);
  if (time) $('#date').value = `${time[1] || '오늘'} ${time[2] || ''}${time[2] ? ' ' : ''}${time[3]}시`.trim();
  const people = text.match(/(혼자|\d+명|\d+\s*~\s*\d+명)/);
  if (people) { const value = people[1] === '혼자' ? '1명' : people[1].replace(/\s/g, ''); const option = [...$('#people').options].find((item) => item.textContent === value); if (option) $('#people').value = option.value; }
  toast(`조건 반영 완료 · ${purpose ? purpose[0] : '방문 목적 확인 필요'} · ${$('#location').value}`);
}
$('#recommendBtn').addEventListener('click', renderResults); $('#parseBtn').addEventListener('click', analyzePrompt); $('#editBtn').addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));
document.querySelectorAll('.nav-link').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.nav-link').forEach((item) => item.classList.remove('active')); button.classList.add('active'); document.querySelectorAll('.view').forEach((item) => item.classList.remove('active-view')); $(`#${button.dataset.view}View`).classList.add('active-view'); if (button.dataset.view === 'history') renderHistory(); })); renderHistory();
async function cloudHistory() { if (!currentUser || !supabaseClient) return; const { data, error } = await supabaseClient.from('visit_history').select('*').order('created_at', { ascending: false }); if (error) return toast(`방문 이력 조회 오류: ${error.message}`); $('#historyList').innerHTML = data.length ? data.map((item) => `<div class="history-item"><div><h3>${item.cafe_name}</h3><small>${item.visit_date} · ${item.purpose || ''} · 작업 효율 ${'★'.repeat(item.work_rating || 0)}${'☆'.repeat(5 - (item.work_rating || 0))}</small></div><button class="history-delete cloud-delete" data-id="${item.id}" type="button">삭제</button></div>`).join('') : '<div class="empty">저장된 방문 이력이 없습니다.</div>'; document.querySelectorAll('.cloud-delete').forEach((button) => button.onclick = async () => { const { error: deleteError } = await supabaseClient.from('visit_history').delete().eq('id', button.dataset.id).eq('user_id', currentUser.id); if (deleteError) return toast(`삭제 오류: ${deleteError.message}`); cloudHistory(); toast('방문 이력을 삭제했습니다.'); }); }
function openCloudRating(button) { if (!currentUser) { toast('방문 이력 저장은 로그인 후 이용할 수 있습니다.'); openAuthModal(); return; } const item = JSON.parse(decodeURIComponent(button.dataset.cafe)); const overlay = document.createElement('div'); overlay.className = 'rating-modal'; overlay.innerHTML = `<div class="rating-dialog"><button type="button" class="rating-close">×</button><h3>작업 효율을 평가해주세요</h3><p>${item.name}</p><div class="rating-stars">${[1,2,3,4,5].map((score) => `<button type="button" data-rating="${score}">★</button>`).join('')}</div><small>별점을 선택하면 Supabase에 저장됩니다.</small></div>`; document.body.appendChild(overlay); const close = () => overlay.remove(); overlay.querySelector('.rating-close').onclick = close; overlay.onclick = (event) => { if (event.target === overlay) close(); }; overlay.querySelectorAll('[data-rating]').forEach((star) => star.onclick = async () => { const score = Number(star.dataset.rating); const { error } = await supabaseClient.from('visit_history').insert({ user_id: currentUser.id, cafe_name: item.name, address: item.address || '', purpose: item.purpose || '', visit_date: item.date, work_rating: score, cafe_data: item }); if (error) return toast(`저장 오류: ${error.message}`); button.textContent = '방문 이력 저장됨'; button.disabled = true; close(); await cloudHistory(); toast(`${score}점으로 Supabase에 저장했습니다.`); }); }
document.addEventListener('click', (event) => { const saveButton = event.target.closest('.history-save'); if (saveButton) { event.preventDefault(); event.stopImmediatePropagation(); openCloudRating(saveButton); } }, true);
document.addEventListener('click', (event) => { const historyTab = event.target.closest('.nav-link[data-view="history"]'); if (historyTab) setTimeout(cloudHistory, 100); }, true);
function openCloudRating(button) { if (!currentUser) { toast('방문 이력 저장은 로그인 후 이용할 수 있습니다.'); openAuthModal(); return; } const item = JSON.parse(decodeURIComponent(button.dataset.cafe)); const overlay = document.createElement('div'); overlay.className = 'rating-modal'; overlay.innerHTML = `<div class="rating-dialog"><button type="button" class="rating-close">×</button><h3>작업 효율을 평가해주세요</h3><p>${item.name}</p><div class="rating-stars">${[1,2,3,4,5].map((score) => `<button type="button" data-rating="${score}">★</button>`).join('')}</div><button type="button" class="rating-confirm" disabled>별점 저장</button></div>`; document.body.appendChild(overlay); const close = () => overlay.remove(); overlay.querySelector('.rating-close').onclick = close; overlay.onclick = (event) => { if (event.target === overlay) close(); }; let selectedScore = 0; const stars = [...overlay.querySelectorAll('[data-rating]')]; const paint = (score) => stars.forEach((star) => star.classList.toggle('active', Number(star.dataset.rating) <= score)); stars.forEach((star) => star.onclick = () => { selectedScore = Number(star.dataset.rating); paint(selectedScore); overlay.querySelector('.rating-confirm').disabled = false; }); overlay.querySelector('.rating-confirm').onclick = async () => { const { error } = await supabaseClient.from('visit_history').insert({ user_id: currentUser.id, cafe_name: item.name, address: item.address || '', purpose: item.purpose || '', visit_date: item.date, work_rating: selectedScore, cafe_data: item }); if (error) return toast(`저장 오류: ${error.message}`); button.textContent = '방문 이력 저장됨'; button.disabled = true; close(); await cloudHistory(); toast(`${selectedScore}점으로 Supabase에 저장했습니다.`); }; }
function openAuthModal() { const overlay = document.createElement('div'); overlay.className = 'auth-modal'; overlay.innerHTML = `<form class="auth-dialog"><button type="button" class="auth-close">×</button><h3>카페 파인더 로그인</h3><input name="code" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" placeholder="4자리 숫자 아이디" required /><input name="password" type="password" inputmode="numeric" pattern="[0-9]{6,}" minlength="6" placeholder="비밀번호(숫자 6자리 이상)" required /><button type="submit">로그인</button><p><button type="button" class="auth-switch">처음인가요? 회원가입</button></p></form>`; document.body.appendChild(overlay); const form = overlay.querySelector('form'); overlay.querySelector('.auth-close').onclick = () => overlay.remove(); overlay.querySelector('.auth-switch').onclick = () => { form.querySelector('h3').textContent = '카페 파인더 회원가입'; form.querySelector('button[type=submit]').textContent = '회원가입'; form.querySelector('.auth-switch').textContent = '이미 계정이 있어요? 로그인'; form.dataset.signup = form.dataset.signup === '1' ? '0' : '1'; }; form.onsubmit = async (event) => { event.preventDefault(); const code = form.code.value.trim(); const password = form.password.value.trim(); if (!/^\d{4}$/.test(code)) return toast('아이디는 숫자 4자리로 입력해주세요.'); if (!/^\d{6,}$/.test(password)) return toast('비밀번호는 숫자 6자리 이상으로 입력해주세요.'); const email = `code-${code}@cafefinder.local`; const result = form.dataset.signup === '1' ? await supabaseClient.auth.signUp({ email, password }) : await supabaseClient.auth.signInWithPassword({ email, password }); if (result.error) { const message = result.error.message.toLowerCase(); if (message.includes('rate limit')) return toast('Supabase 이메일 제한에 걸렸습니다. Confirm email을 끄고 잠시 후 다시 시도해주세요.'); return toast(result.error.message); } overlay.remove(); toast(form.dataset.signup === '1' ? '4자리 숫자 아이디로 회원가입했습니다.' : '로그인했습니다.'); }; }
function openCloudRating(button) { if (!currentUser) { toast('방문 이력 저장은 로그인 후 이용할 수 있습니다.'); openAuthModal(); return; } const item = JSON.parse(decodeURIComponent(button.dataset.cafe)); const overlay = document.createElement('div'); overlay.className = 'rating-modal'; overlay.innerHTML = `<div class="rating-dialog"><button type="button" class="rating-close">×</button><h3>작업 효율을 평가해주세요</h3><p>${item.name}</p><div class="rating-stars">${[1,2,3,4,5].map((score) => `<button type="button" data-rating="${score}">★</button>`).join('')}</div><button type="button" class="rating-confirm" disabled>별점 저장</button></div>`; document.body.appendChild(overlay); const close = () => overlay.remove(); overlay.querySelector('.rating-close').onclick = close; overlay.onclick = (event) => { if (event.target === overlay) close(); }; let selectedScore = 0; const stars = [...overlay.querySelectorAll('[data-rating]')]; const paint = (score) => stars.forEach((star) => star.classList.toggle('active', Number(star.dataset.rating) <= score)); stars.forEach((star) => { star.onmouseenter = () => paint(Number(star.dataset.rating)); star.onmouseleave = () => paint(selectedScore); star.onclick = () => { selectedScore = Number(star.dataset.rating); paint(selectedScore); overlay.querySelector('.rating-confirm').disabled = false; }; }); overlay.querySelector('.rating-confirm').onclick = async () => { const { error } = await supabaseClient.from('visit_history').insert({ user_id: currentUser.id, cafe_name: item.name, address: item.address || '', purpose: item.purpose || '', visit_date: item.date, work_rating: selectedScore, cafe_data: item }); if (error) return toast(`저장 오류: ${error.message}`); button.textContent = '방문 이력 저장됨'; button.disabled = true; close(); await cloudHistory(); toast(`${selectedScore}점으로 Supabase에 저장했습니다.`); }; }
async function cloudHistory() { if (!currentUser || !supabaseClient) return; const { data, error } = await supabaseClient.from('visit_history').select('*').order('created_at', { ascending: false }); if (error) return toast(`방문 이력 조회 오류: ${error.message}`); cloudRatedKeys = new Set(data.map((item) => cafeKey(item.cafe_name, item.address))); const unique = [...new Map(data.map((item) => [cafeKey(item.cafe_name, item.address), item])).values()].sort((a, b) => (b.work_rating || 0) - (a.work_rating || 0)); $('#historyList').innerHTML = unique.length ? unique.map((item) => `<div class="history-item"><div><h3>${item.cafe_name}</h3><small>${item.visit_date} · ${item.purpose || ''} · 작업 효율 ${'★'.repeat(item.work_rating || 0)}${'☆'.repeat(5 - (item.work_rating || 0))}</small></div><button class="history-delete cloud-delete" data-id="${item.id}" type="button">삭제</button></div>`).join('') : '<div class="empty">저장된 방문 이력이 없습니다.</div>'; document.querySelectorAll('.history-save').forEach((button) => { const item = JSON.parse(decodeURIComponent(button.dataset.cafe)); if (cloudRatedKeys.has(cafeKey(item.name, item.address))) { button.textContent = '평가 완료'; button.disabled = true; } }); document.querySelectorAll('.cloud-delete').forEach((button) => button.onclick = async () => { const { error: deleteError } = await supabaseClient.from('visit_history').delete().eq('id', button.dataset.id).eq('user_id', currentUser.id); if (deleteError) return toast(`삭제 오류: ${deleteError.message}`); cloudHistory(); toast('방문 이력을 삭제했습니다.'); }); }
