const http = require('http');
const fs = require('fs');
const path = require('path');
const root = __dirname;
const envPath = path.join(root, '.env');
if (fs.existsSync(envPath)) for (const line of fs.readFileSync(envPath, 'utf8').split(/\r?\n/)) { const m = line.match(/^\s*([^#=]+)\s*=\s*(.*?)\s*$/); if (m && !process.env[m[1]]) process.env[m[1]] = m[2]; }
async function searchWithOpenAI(query) {
  if (!process.env.OPENAI_API_KEY) return [];
  const cached = searchCache.get(query);
  if (cached && cached.expiresAt > Date.now()) return cached.results;
  const prompt = `전국 카페 추천 서비스의 검색 결과를 만들어줘. 웹 검색으로 최신 정보를 확인하고, 다음 검색 조건에 맞는 일반 카페 정확히 3곳(Top 3)을 찾아줘. 스터디카페, 독서실, 스터디룸, 무인 스터디 공간, 학원형 스터디 공간은 반드시 제외해. 검색 결과가 부족해도 해당 지역의 일반 카페를 추가로 찾아 반드시 3곳을 반환해: ${query}\n반드시 JSON 배열만 반환해. 각 항목은 name, address, phone, category, url, source, reason, imageUrl, businessHours, crowdLevel, seatType, noiseLevel, outlet, signatureMenu 필드를 포함해. imageUrl은 실제 카페 외관·간판 사진의 직접 이미지 URL을 확인할 수 있을 때만 넣고, 아니면 빈 문자열로 둬. crowdLevel은 현재 시간대 혼잡도를 여유/보통/혼잡/정보 확인 필요 중 하나로 표시해. businessHours는 영업시간, seatType은 자리 유형, noiseLevel은 조용함/보통/시끌벅적 중 하나, outlet은 콘센트 있음/일부 있음/없음 중 하나, signatureMenu는 대표 메뉴를 넣어. 확인하지 못한 값은 "정보 확인 필요"로 둬. source는 "OPENAI WEB SEARCH"로 넣어.`;
  const response = await fetch('https://api.openai.com/v1/responses', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${process.env.OPENAI_API_KEY}` }, body: JSON.stringify({ model: 'gpt-5.6-luna', tools: [{ type: 'web_search' }], input: prompt }) });
  if (!response.ok) throw Error(`OpenAI API 오류: ${response.status}`); const data = await response.json(); const text = data.output_text || (data.output || []).flatMap(item => item.content || []).map(item => item.text || '').join(''); const match = text.match(/\[[\s\S]*\]/); if (!match) throw Error('OpenAI가 구조화된 검색 결과를 반환하지 않았습니다.'); const results = JSON.parse(match[0]); searchCache.set(query, { results, expiresAt: Date.now() + 15 * 60 * 1000 }); return results;
}
async function geocode(name, address, location) { const cleaned = String(address || '').replace(/\b(B\d+|지하\s*\d+층?|\d+층)\b/gi, '').replace(/\([^)]*\)/g, '').replace(/,\s*,/g, ',').trim(); const queries = [cleaned, [cleaned, location].filter(Boolean).join(', '), [location, name].filter(Boolean).join(', ')].filter(Boolean); for (const query of queries) { const response = await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=kr&q=${encodeURIComponent(query)}`, { headers: { 'User-Agent': 'CafeFinder/1.0 contact@cafefinder.local', Accept: 'application/json' } }); if (!response.ok) continue; const place = (await response.json())[0]; if (place) return { lat: place.lat, lon: place.lon, display_name: place.display_name }; } return {}; }
const searchCache = new Map();
const server = http.createServer(async (req, res) => { const u = new URL(req.url, 'http://localhost:8000'); res.setHeader('Access-Control-Allow-Origin', '*'); try { if (u.pathname === '/api/geocode') { const name = u.searchParams.get('name') || ''; const address = u.searchParams.get('address') || ''; const location = u.searchParams.get('location') || ''; if (!name && !address && !location) throw Error('주소가 필요합니다.'); const result = await geocode(name, address, location); res.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'public, max-age=3600' }); return res.end(JSON.stringify(result)); } if (u.pathname === '/api/search') { const q = u.searchParams.get('query'); if (!q) throw Error('검색어가 필요합니다.'); const results = await searchWithOpenAI(q); if (!results.length) throw Error('OPENAI_API_KEY가 설정되지 않았거나 검색 결과가 없습니다.'); res.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8' }); return res.end(JSON.stringify({ results })); } const file = u.pathname === '/' ? '/index.html' : u.pathname; const filePath = path.join(root, file); if (!filePath.startsWith(root) || !fs.existsSync(filePath)) { res.writeHead(404); return res.end('Not found'); } const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8' }; res.writeHead(200, { 'Content-Type': types[path.extname(filePath)] || 'application/octet-stream' }); return fs.createReadStream(filePath).pipe(res); } catch (error) { res.writeHead(500, { 'Content-Type': 'application/json; charset=utf-8' }); return res.end(JSON.stringify({ error: error.message })); } });
server.listen(process.env.PORT || 8000, () => console.log(`Cafe Finder running on http://localhost:${process.env.PORT || 8000}`));
